Template example
Componolit/capdpa pull request #70
Opened 2019-01-30 10:35 UTC by jklmnn

I adapted the example to use a template (and fixed the incompatibilities between my original example and staging). I also adapted the example in the readme to explain the actual available one.

2019-01-30 11:48 UTC, senier requested changes

2019-01-30 11:48 UTC, senier commented on README.md
> +package Number_T_Int
Shouldn't this package be a child of `Example`?

2019-01-31 10:29 UTC, jklmnn commented on README.md
> +package Number_T_Int
This is a subpackage of `Example` and I only took this part of the file.

2019-01-31 10:57 UTC, senier approved these changes

2019-01-31 10:58 UTC, merged